
import os

# Find the model file in the models directory
MODEL_DIR = os.path.join(os.path.dirname(__file__), "models")
MODEL_PATH = os.path.join(MODEL_DIR, "final_crime_classifier.pth")

# Define class names for crime detection
CLASS_NAMES = ['Abuse', 'Arrest', 'Arson', 'Assault']

# Define detailed descriptions for each crime type
CRIME_DESCRIPTIONS = {
    "Abuse": """The video appears to be footage captured by a fixed-position surveillance camera in an outdoor setting, possibly near a convenience store or residential area during nighttime. The lighting is dim, but a few artificial light sources—like a nearby streetlamp or building lights—faintly illuminate the scene. Two individuals are central to the events unfolding. One person, dressed in a light-colored jacket, displays assertive or aggressive body language, frequently moving toward the second person in a confrontational manner. The second individual, wearing darker clothing, appears more passive and is seen stepping back or avoiding direct engagement. As the interaction progresses, the dominant figure becomes increasingly physical—gesturing emphatically, moving into the personal space of the other individual, and possibly shoving or striking them. The victim shows signs of discomfort and retreat, suggesting this is not a mutual argument but a one-sided confrontation. No third parties intervene throughout the video, and the isolated location contributes to the tense atmosphere. A vehicle is seen briefly in the background, but it does not stop or affect the scene. Overall, the visual cues, body language, and the setting strongly indicate an abusive encounter, likely verbal at first and escalating into physical aggression. The lack of intervention and the evident distress of the second person reinforce the classification of this scenario as an abuse incident.""",
    
    "Arrest": """The video appears to depict a surveillance-style recording set in a relatively dim, outdoor urban environment—likely during nighttime or late evening. It opens with a quiet street scene, featuring minimal activity and low lighting. As time progresses, a lone figure enters the frame, moving with deliberate caution. The person, dressed in dark clothing, glances around frequently, suggesting heightened awareness or a desire to avoid detection. Around the middle of the video, the individual's behavior becomes more suspicious. They approach a parked vehicle and begin interacting with it, possibly attempting to break in. The lighting conditions make it difficult to discern fine details, but their posture and movements are consistent with tampering or forced entry. The video then shows the figure partially obscured, possibly crouching or shielding their actions from any potential onlookers or cameras. In the later frames, the individual appears to flee the scene abruptly, possibly in response to an unexpected stimulus—such as a sound, a passing car, or perhaps realizing they are being recorded. The hasty exit supports the assumption of illicit activity. Throughout the clip, the camera remains stationary, and no additional individuals appear in the frame. The grainy quality and limited resolution lend the footage an authentic surveillance feel, enhancing the impression that this recording could serve as part of a criminal investigation. Overall, the video documents what appears to be a covert, potentially criminal act captured on a basic security camera setup. Its contents may be useful for identifying suspicious behavior, especially if combined with additional footage or eyewitness testimony.""",

    "Arson": """The initial frame shows a relatively quiet street or alleyway, possibly in an urban setting. The lighting suggests early morning or late evening, and the camera angle appears fixed, typical of a security camera. There is minimal activity in this first segment, creating a calm yet slightly tense atmosphere. As the video progresses, a figure enters the frame—dressed in dark clothing and moving quickly. This person's posture and behavior seem covert, as if attempting to avoid detection. The next frame highlights a key moment where the individual approaches a stationary object—possibly a vehicle or a shop entrance. Their actions grow more deliberate and hurried, suggesting a potential break-in or theft. In subsequent scenes, the person either flees the area or is confronted, though the quality of the footage makes it difficult to determine facial details or exact interactions. The final frame hints at resolution, with the person either out of the frame or possibly being approached by another figure—perhaps a bystander or security personnel. Overall, the video captures a condensed narrative of a likely criminal act unfolding in real time. The grainy, low-resolution style contributes to the realism, resembling footage that could be used as evidence. The sequence effectively portrays rising tension, action, and aftermath, offering insight into surveillance use in urban crime monitoring.""",

    "Assault": """The video appears to be recorded from a stationary surveillance camera overlooking a relatively secluded urban or semi-urban alleyway. It is approximately one minute long and captured at night or in low-light conditions, which adds a gritty, realistic tone to the footage. Initially, the scene is calm, with no visible movement. A streetlamp provides limited illumination, casting elongated shadows across the pavement. Roughly ten seconds into the clip, a lone individual enters the frame from the left side, walking at a brisk pace. The person is dressed in dark, loose-fitting clothing and appears to be wearing a hood, which obscures part of their face. Their demeanor is tense and watchful, with repeated glances over the shoulder, suggesting a sense of urgency or anxiety. Midway through the video, the figure stops beside a parked vehicle and begins interacting with the driver's side door. The movements are precise and hurried—suggesting either forced entry or a quick unlocking process. This action takes place in partial shadow, adding to the clandestine nature of the act. Moments later, the car's interior lights briefly flash on, indicating the door may have been opened. As the video nears its end, the individual slips into the vehicle and sits still for a moment before the headlights flicker. The person then drives away, exiting the frame from the right side. The act is swift and deliberate, implying familiarity with the process and suggesting it may be a car theft or unauthorized use. Overall, the video portrays a likely criminal act captured in real-time. The figure's guarded movements, time of activity, and methodical actions all contribute to the impression of illicit behavior, potentially valuable for investigative purposes."""
}
