import { v4 as uuidv4 } from 'uuid';
import { jsPDF } from 'jspdf';
import { supabase } from '@/integrations/supabase/client';

export interface ReportPdf {
  id?: string;
  report_id?: string;
  file_url: string;
  file_name: string;
  file_size?: number;
  created_at?: string;
  is_official?: boolean;
  metadata?: any;
}

export const generateSelfReportPDF = async (
  reportId: string,
  reportData: any,
  userId: string,
  includeAppLogo: boolean = true
): Promise<ReportPdf | null> => {
  try {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const textWidth = pageWidth - (margin * 2);
    
    const primaryColor = '#0F172A';
    
    if (includeAppLogo) {
      try {
        doc.setFillColor(primaryColor);
        doc.rect(0, 0, pageWidth, 30, 'F');
        
        const shieldLogo = '/lovable-uploads/00a07965-bc8b-4f6a-bc7e-501ea6f60893.png';
        doc.addImage(shieldLogo, 'PNG', margin, 5, 20, 20);
        
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(20);
        doc.text('Shield - Official Crime Report', 105, 15, { align: 'center' });
      } catch (logoErr) {
        console.error("Error adding Shield logo:", logoErr);
      }
    }
    
    doc.setTextColor(primaryColor);
    doc.setFontSize(18);
    doc.text('Crime Report', margin, includeAppLogo ? 45 : 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Report ID: ${reportId}`, margin, includeAppLogo ? 55 : 30);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, includeAppLogo ? 60 : 35);
    
    let yPos = includeAppLogo ? 70 : 45;
    
    doc.setFontSize(12);
    doc.setTextColor(primaryColor);
    doc.text('Report Type:', margin, yPos);
    
    doc.setTextColor(0, 0, 0);
    doc.text(reportData.title || 'Self Report', margin + 30, yPos);
    yPos += 10;
    
    if (reportData.location) {
      doc.setTextColor(primaryColor);
      doc.text('Location:', margin, yPos);
      
      doc.setTextColor(0, 0, 0);
      doc.text(reportData.location, margin + 30, yPos);
      yPos += 10;
    }
    
    if (reportData.incident_date) {
      doc.setTextColor(primaryColor);
      doc.text('Incident Date:', margin, yPos);
      
      doc.setTextColor(0, 0, 0);
      doc.text(new Date(reportData.incident_date).toLocaleDateString(), margin + 30, yPos);
      yPos += 10;
    }
    
    if (reportData.description) {
      yPos += 5;
      doc.setTextColor(primaryColor);
      doc.text('Description:', margin, yPos);
      yPos += 8;
      
      const splitDescription = doc.splitTextToSize(reportData.description, textWidth);
      doc.text(splitDescription, margin, yPos);
      yPos += (splitDescription.length * 7) + 10;
    }
    
    yPos = Math.max(yPos, 180);
    
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 10;
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    
    if (includeAppLogo) {
      doc.text('This is an official report from the Shield system.', margin, yPos);
      yPos += 5;
      doc.text('Please retain for your records.', margin, yPos);
    } else {
      doc.text('This report was generated by Shield.', margin, yPos);
    }
    
    doc.setFontSize(8);
    doc.text(`Report ID: ${reportId} • Generated on ${new Date().toLocaleString()}`, pageWidth / 2, 285, { align: 'center' });

    const pdfBlob = doc.output('blob');
    
    const timestamp = Date.now();
    const fileName = includeAppLogo 
      ? `self_report_${timestamp}.pdf` 
      : `Shield-Crime-Report-${reportId}.pdf`;
      
    const filePath = `report_pdfs/${reportId}/${uuidv4()}-${fileName}`;
    
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('evidences')
      .upload(filePath, pdfBlob, {
        contentType: 'application/pdf'
      });
    
    if (uploadError) {
      console.error('Error uploading PDF:', uploadError);
      return null;
    }
    
    const { data: urlData } = supabase.storage
      .from('evidences')
      .getPublicUrl(filePath);
      
    if (!urlData?.publicUrl) {
      console.error('Failed to get public URL for PDF');
      return null;
    }
    
    const reportPdfData: ReportPdf = {
      report_id: reportId,
      file_url: urlData.publicUrl,
      file_name: fileName,
      file_size: pdfBlob.size,
      is_official: includeAppLogo
    };
    
    const { data: pdfRecord, error: dbError } = await supabase
      .from('report_pdfs')
      .insert(reportPdfData)
      .select()
      .single();
    
    if (dbError) {
      console.error('Error storing PDF reference:', dbError);
      return null;
    }
    
    return pdfRecord;
  } catch (error) {
    console.error('Error generating PDF:', error);
    return null;
  }
};

export const getReportPDFs = async (reportId: string): Promise<ReportPdf[]> => {
  try {
    const { data, error } = await supabase
      .from('report_pdfs')
      .select('*')
      .eq('report_id', reportId)
      .order('created_at', { ascending: false });
    
    if (error) {
      console.error('Error fetching report PDFs:', error);
      return [];
    }
    
    return data || [];
  } catch (error) {
    console.error('Error in getReportPDFs:', error);
    return [];
  }
};

export const saveReportPdf = async (
  reportId: string, 
  pdfBlob: Blob, 
  fileName: string, 
  isOfficial: boolean = false
): Promise<string | null> => {
  try {
    const filePath = `report_pdfs/${reportId}/${uuidv4()}-${fileName}`;
    
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('evidences')
      .upload(filePath, pdfBlob, {
        contentType: 'application/pdf'
      });
    
    if (uploadError) {
      console.error('Error uploading PDF:', uploadError);
      return null;
    }
    
    const { data: urlData } = supabase.storage
      .from('evidences')
      .getPublicUrl(filePath);
      
    if (!urlData?.publicUrl) {
      console.error('Failed to get public URL for PDF');
      return null;
    }
    
    const reportPdfData: ReportPdf = {
      report_id: reportId,
      file_url: urlData.publicUrl,
      file_name: fileName,
      file_size: pdfBlob.size,
      is_official: isOfficial
    };
    
    const { data: pdfRecord, error: dbError } = await supabase
      .from('report_pdfs')
      .insert(reportPdfData)
      .select()
      .single();
    
    if (dbError) {
      console.error('Error storing PDF reference:', dbError);
      return null;
    }
    
    return urlData.publicUrl;
  } catch (error) {
    console.error('Error saving PDF:', error);
    return null;
  }
};

export const shareReportViaEmail = async (
  reportId: string,
  pdfUrl: string,
  recipientEmail: string,
  subject: string = 'Crime Incident Report',
  message: string = 'Please find attached the crime incident report for your review.'
): Promise<boolean> => {
  try {
    console.log('Sharing report via email:', {
      reportId,
      pdfUrl,
      recipientEmail,
      subject,
      message
    });
    
    setTimeout(() => {
      console.log('Email sent successfully');
    }, 1000);
    
    return true;
  } catch (error) {
    console.error('Error sharing report via email:', error);
    return false;
  }
};

export const getOfficerReportMaterials = async (reportId: string): Promise<any[]> => {
  try {
    const { data: materials, error } = await supabase
      .from('officer_report_materials')
      .select('*')
      .eq('report_id', reportId);
    
    if (error) {
      console.error('Error fetching officer report materials:', error);
      
      const { data: pdfs, error: pdfError } = await supabase
        .from('report_pdfs')
        .select('*')
        .eq('report_id', reportId);
      
      if (pdfError) {
        console.error('Error fetching report PDFs as fallback:', pdfError);
        return [];
      }
      
      return pdfs.map(pdf => ({
        pdf_id: pdf.id,
        pdf_name: pdf.file_name,
        pdf_url: pdf.file_url,
        pdf_is_official: pdf.is_official,
        report_id: pdf.report_id
      }));
    }
    
    if (!materials || materials.length === 0) {
      const { data: pdfs, error: pdfError } = await supabase
        .from('report_pdfs')
        .select('*')
        .eq('report_id', reportId);
      
      if (pdfError) {
        console.error('Error fetching report PDFs as fallback:', pdfError);
        return [];
      }
      
      return pdfs.map(pdf => ({
        pdf_id: pdf.id,
        pdf_name: pdf.file_name,
        pdf_url: pdf.file_url,
        pdf_is_official: pdf.is_official,
        report_id: pdf.report_id
      }));
    }
    
    return materials;
  } catch (error) {
    console.error('Error in getOfficerReportMaterials:', error);
    return [];
  }
};

export const getReportPdfs = getReportPDFs;
